package com.mapfre.mifel.vida.helper;

import com.google.common.util.concurrent.CycleDetectingLockFactory.Policies;
import com.mapfre.mifel.vida.model.request.IssueRequest;
import com.mapfre.mifel.vida.model.ul.ContractorData;
import com.mapfre.mifel.vida.repository.e2e.IThirdRepository;
import com.mapfre.mifel.vida.repository.esa.IMifelVidaULRepository;
import com.mapfre.mifel.vida.service.VidaULService;
import com.mapfre.mifel.vida.utils.HostUtil;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.*;
import static com.mapfre.mifel.vida.utils.VidaULContants.*;

import static com.mapfre.mifel.vida.utils.BeneficiarioConstants.P_COD_CIA;

public class EmisionVidaFM {
    @Autowired
    IMifelVidaULRepository iMifelVidaULRepository;

    @Autowired
    IThirdRepository iThirdRepository;
    
    @Autowired
    VidaULService service;

    private Boolean checkSF = false;

    private static final Logger logger = LogManager.getLogger(EmisionVidaFM.class);

    public EmisionVidaFM(IMifelVidaULRepository iMifelVidaULRepository, IThirdRepository iThirdRepository) {
        this.iMifelVidaULRepository = iMifelVidaULRepository;
        this.iThirdRepository = iThirdRepository;
    }

    public Boolean getCheckSF() {
        return checkSF;
    }

    public void setCheckSF(Boolean checkSF) {
        this.checkSF = checkSF;
    }

    public String setTaxData(IssueRequest request) {

        String result = "";
        Integer procVal = 0;
        String msgVal = "";

        logger.info("Setting Tax Data");


        ContractorData contractorData = request.getContractorData();
        logger.info("contractorData: {}", contractorData);
        String taxSysCode = contractorData.getTaxSystemCode().orElse("");
        String sTaxSystemCode = (contractorData.getTaxSystemCode() == null || contractorData.getTaxSystemCode().equals("")) ? "0" : taxSysCode;
//        String sTaxZipCode = (contractorData.getTaxZipCode() == null ) ? "" : contractorData.getTaxZipCode();
        String sTaxZipCode = contractorData.getTaxZipCode().orElse("");
        
        String physMca = contractorData.getPersonType();
        
        String middleName = contractorData.getContractingMiddleName().orElse("");
        String regimen = contractorData.getCorporateRegime().orElse("");

        String dataInfo =  physMca.equals("S")? middleName: regimen;
        logger.info("dataInfo: {}", dataInfo);

        Date currentDate= new Date();
        
        String name = request.getContractorData().getContractingFistName().orElse("");
        
        String lastName =  request.getContractorData().getContractingLastName().orElse("");
        String rfc = request.getContractorData().getDocumCode().orElse("XAXX010101000");
        String address1 = request.getContractorData().getAddressName1().orElse("");
        String address2 = request.getContractorData().getAddressName2().orElse("");
        String address3 = request.getContractorData().getAddressName3().orElse("");
        String postalCode = request.getContractorData().getPostalCode().orElse("");
        String stateCode = request.getContractorData().getStateCode().orElse("");
        String provinceCode = request.getContractorData().getProvinceCode().orElse("");
        String countryCode = request.getContractorData().getCountryCode().orElse("");
        String telephone = request.getContractorData().getTelephoneNumber().orElse("");

        Map<String, String> mapRes = iThirdRepository.cargaDatos(P_COD_CIA
                , "RFC"
                , rfc
                , contractorData.getPersonType()
                , Integer.valueOf(sTaxSystemCode)
                , name
                , dataInfo
                , lastName
                , address1
                , address2
                , ""
                , ""
                , sTaxZipCode
                , Integer.valueOf(contractorData.getProvinceCode().orElse("0"))
                , Integer.valueOf(contractorData.getStateCode().orElse("0"))
                , countryCode
                , ""
                , currentDate
                , procVal
                , msgVal);

        logger.info("|procval - msgVal| fron cargaDatos: |{} - {}|", procVal, msgVal);

        return msgVal;

    }


    public String getEmision(Map<String, String> mapPoliza, List<Map<String, String>> listaDatosVariables, List<Map<String, String>> listaDatosVariablesCoverage, List<Map<String, String>> listCoberturas, Map<String, String> mapContratante, Map<String, String> mapAsegurado, List<Map<String, String>> listaBeneficiarios, Map<String, String> mapDatosBancarios, String strCotizacion) {
        String strResultado = "";
        try {
            Map<String, Object> drEmision =this.setEmision(mapPoliza, listaDatosVariables, listaDatosVariablesCoverage, listCoberturas, mapContratante, mapAsegurado, listaBeneficiarios, mapDatosBancarios,  strCotizacion);

            if(drEmision.get("pnum_poliza") != null){
                strResultado= String.valueOf(drEmision.get("pnum_poliza"));
            }else{
                strResultado = "No se pudo realizar la Emisión de su Póliza, faltan datos: " + drEmision.get("ptxt_error").toString();
                throw new Exception(strResultado);
            }
        }catch(Exception e){
            logger.info("No se pudo realizar la Emisión de su Póliza " + e.getMessage());
        }
        return strResultado;
    }

    private Map<String, Object> setEmision(Map<String, String> mapPoliza, List<Map<String, String>> listaDatosVariables,
    									List<Map<String, String>> listaDatosVariablesCoverage ,List<Map<String, String>> listCoberturas, Map<String, String> mapContratante,
                                           Map<String, String> mapAsegurado, List<Map<String, String>> listaBeneficiarios,
                                           Map<String, String> mapDatosBancarios, String strCotizacion) {

        Map<String, String> DATOS_AUX;
        P1001331 objP1001331 = new P1001331();
        P2000030 objP2000030 = new P2000030(mapPoliza.get("COD_AGT"));
        P2000031 objP2000031 = new P2000031();
        P2000025 objP2000025 = new P2000025();
        P2000020 objP2000020 = new P2000020();
        P2000060 objP2000060 = new P2000060();
        P2300061_MMX objP2300061_MMX = new P2300061_MMX();
        //Dim objP2990706_MMX As New P2990706_MMX
        P2000040 objP2000040 = new P2000040(mapPoliza.get("COD_RAMO"));
        W2990708 objW2990708 = new W2990708(mapPoliza.get("COD_AGT"), mapDatosBancarios.get("TIP_CUENTA"));
        W2990709 objW2990709 = new W2990709(mapPoliza.get("TIP_GESTOR"), mapPoliza.get("COD_AGT"));
        HashMap<String, Object> drResultado= new LinkedHashMap<>();
        int rowNum=0;
        String modality = null;
        try {
            /** Datos Poliza */
            /** Datos Variables */
            /** Datos Cobertura */
            /** Datos Contratante */
            /** Datos Solicitante */
            /** Datos Beneficiario */
            /** Datos Bancarios */

            StringBuffer cadenaXml = new StringBuffer();
            String COD_AGT = "";
            String codRamo = mapPoliza.get("COD_RAMO");
            String TIP_CUENTA = "";
            String TIP_GESTOR = "";

            /** Encabezado del XML ************************************************************************************/
            if (strCotizacion.equals("C")) {
                cadenaXml.append("<XML ACCION=\"C\" COD_ORIGEN=\"1\" COD_RAMO=\"");
            } else {
                cadenaXml.append("<XML ACCION=\"P\" COD_ORIGEN=\"1\" COD_RAMO=\"");
            }
            cadenaXml.append(codRamo);
            cadenaXml.append("\" NUM_POLIZA=\"\"" + ">");

            /** En caso de que el Tipo de pago sea con Cta BAnco o TC se modifica el cod_gestor  */
            if (!mapPoliza.get("TIP_GESTOR").trim().equals("AG")) {
                mapPoliza.replace("COD_GESTOR", mapDatosBancarios.get("COD_ENTIDAD")+ mapDatosBancarios.get("COD_ENTIDAD"));
            }
            mapPoliza.put("COD_USR", USER_CODE);
            mapPoliza.put("PCT_AGT", "100");
            mapPoliza.put("TIP_REGULARIZA", "0");
            mapPoliza.put("PCT_REGULARIZA", "0");
            mapPoliza.put("COD_ENVIO", "1");
            mapPoliza.put("COD_MON", "1");
            
            //mapPoliza.put("NUM_CONTRATO",null);
            //mapPoliza.put("NUM_POLIZA_GRUPO",null);
            /** Se Genera el Nodo de la Tabla P2000030 */
            rowNum = 1;
            objP2000030.setDatos(mapPoliza);
            cadenaXml.append(setInicio("P2000030"));
            cadenaXml.append(objP2000030.getXml(rowNum));
            cadenaXml.append(setFin());

            /** Se Genera el Nodo de la Tabla P2000031 */
            rowNum = 1;
            cadenaXml.append(setInicio("P2000031"));
            objP2000031.setDatos(mapAsegurado);
            cadenaXml.append(objP2000031.getXml(rowNum));
            cadenaXml.append(setFin());
            
            /** Se Genera el Nodo de la Tabla P2000025 */
            //generaNodoP2000025(cadenaXml, objP2000025);
            rowNum = 1;
            cadenaXml.append(setInicio("P2000025"));
            for (Map<String, String> hashDATO: listaDatosVariablesCoverage) {
                //DATOS_AUX = hashDATO;
                objP2000025.setDatos(hashDATO);
                cadenaXml.append(objP2000025.getXml(rowNum));
                rowNum ++;
            }
            cadenaXml.append(setFin());

            /** Se Genera el Nodo de la Tabla P2000020 */
            rowNum = 1;
            cadenaXml.append(setInicio("P2000020"));
            for (Map<String, String> hashDATO: listaDatosVariables) {
                //DATOS_AUX = hashDATO;
                objP2000020.setDatos(hashDATO);
                cadenaXml.append(objP2000020.getXml(rowNum));
                rowNum ++;
            }
           
            cadenaXml.append(setFin());

            /** Se Genera el Nodo de la Tabla P2000060 */
            cadenaXml.append(setInicio("P2000060"));
            DATOS_AUX = new Hashtable<>();
            /** Solicitante */
            rowNum = 1;
            DATOS_AUX.put("TIP_BENEF", "2");
            DATOS_AUX.put("NUM_SECU", "1");
            DATOS_AUX.put("TIP_DOCUM", mapAsegurado.get("TIP_DOCUM"));
            DATOS_AUX.put("COD_DOCUM", mapAsegurado.get("COD_DOCUM"));
            DATOS_AUX.put("PCT_PARTICIPACION", "");
            objP2000060.setDatos(DATOS_AUX);
            cadenaXml.append(objP2000060.getXml(rowNum));

            if(getCheckSF().equals(true)){
                DATOS_AUX = mapAsegurado;
                DATOS_AUX.put("TIP_BENEF", "10");
                objP2000060.setDatos(DATOS_AUX);
                cadenaXml.append(objP2000060.getXml(rowNum));
            }
            /** Beneficiario */
            if (listaBeneficiarios.size() > 0 ){
                rowNum = 2;
                for (Map<String, String> hashDATO: listaBeneficiarios) {
                    DATOS_AUX = hashDATO;
                    objP2000060.setDatos(DATOS_AUX);
                    cadenaXml.append(objP2000060.getXml(rowNum));
                    rowNum ++;
                }
            }
            cadenaXml.append(setFin());

            /** Se Genera el Nodo de la Tabla P2000040 */
            rowNum = 1;
            cadenaXml.append(setInicio("P2000040"));
            for (Map<String,String>  hashDATO: listCoberturas) {
                DATOS_AUX = hashDATO;
                objP2000040.setDatos(DATOS_AUX);
                cadenaXml.append(objP2000040.getXml(rowNum));
                rowNum ++;
            }
            cadenaXml.append(setFin());

            /**
             * Se Genera los Nodos de la Tabla P1001331
             *     Asegurado
             *     ROW_NUM = 1
             *     objP1001331.setDatos(DATOS_ASEG)
             *     objXML.Append("<TABLE NAME=""P1001331""><ROWSET>")
             *     objXML.Append(objP1001331.getXML(ROW_NUM))
             *
             *     Beneficiario
             *     If DATOS_BENEF.Count > 0 Then
             *         ROW_NUM = 2
             *
             *         For Each hashDATO In DATOS_BENEF
             *             DATOS_AUX = hashDATO.Clone()
             *             objP1001331.setDatos(DATOS_AUX)
             *             objXML.Append(objP1001331.getXML(ROW_NUM))
             *             ROW_NUM = ROW_NUM + 1
             *         Next
             *     End If
             *     objXML.Append("</ROWSET></TABLE>")
             */

            /** Datos de Cta Banco o TC */
            if(mapDatosBancarios.size() > 0) {
                /**
                 *  objXML.Append("<TABLE NAME=""P2990706_MMX""><ROWSET>")
                 *  ROW_NUM = 1
                 *  DATOS_BANCO.Add("TIP_GESTOR", DATOS_POLIZA("TIP_GESTOR").ToString())
                 *  objP2990706_MMX.setDatos(DATOS_BANCO)
                 *  objXML.Append(objP2990706_MMX.getXML(ROW_NUM))
                 *  objXML.Append("</ROWSET></TABLE>")
                 */

                /**TABLA W2990708 */
                rowNum = 1;
                objW2990708.setDatos(mapDatosBancarios);
                cadenaXml.append(setInicio("W2990708_MMX"));
                cadenaXml.append(objW2990708.getXml(rowNum));
                cadenaXml.append(setFin());

                /** TABLA PW990709 */
                rowNum = 1;
                objW2990709.setDatos(mapDatosBancarios);
                cadenaXml.append(setInicio("W2990709_MMX"));
                cadenaXml.append(objW2990709.getXml(rowNum));
                cadenaXml.append(setFin());
            }
            cadenaXml.append("</XML>");

            String XML;
            XML = cadenaXml.toString();
            String userC = USER_CODE + "_" + getClientHost1().replace(".", "_");
            logger.info("xml-->"+cadenaXml.toString());
            //drResultado = iThirdRepository.setCotizacionEmision(cadenaXml.toString(), userC );
            String xml = cadenaXml.toString();
            //xml = "<?xml version=\"1.0\" ?><XML NUM_POLIZA=\"\" COD_ORIGEN=\"1\" ACCION=\"C\" COD_RAMO=\"112\"><TABLE NAME=\"P2000030\"><ROWSET><ROW><ANIOS_MAX_DURACION>1</ANIOS_MAX_DURACION><CANT_RENOVACIONES>0</CANT_RENOVACIONES><COD_AGT>99998</COD_AGT><COD_AGT2></COD_AGT2><COD_AGT3></COD_AGT3><COD_AGT4></COD_AGT4><COD_CIA>1</COD_CIA><COD_COMPENSACION>1</COD_COMPENSACION><COD_CUADRO_COM>81</COD_CUADRO_COM><COD_DOCUM>00000000000117032188</COD_DOCUM><COD_ENVIO>1</COD_ENVIO><COD_FRACC_PAGO>1</COD_FRACC_PAGO><COD_GESTOR>99998</COD_GESTOR><COD_MON>1</COD_MON><COD_NIVEL1></COD_NIVEL1><COD_NIVEL2></COD_NIVEL2><COD_NIVEL3></COD_NIVEL3><COD_NIVEL3_CAPTURA>4920</COD_NIVEL3_CAPTURA><COD_RAMO>112</COD_RAMO><COD_SECTOR>1</COD_SECTOR><COD_USR>APPSEGA</COD_USR><DURACION_PAGO_PRIMA>1</DURACION_PAGO_PRIMA><FEC_ACTU>29/02/2024</FEC_ACTU><FEC_EFEC_POLIZA>28/02/2024</FEC_EFEC_POLIZA><FEC_EFEC_SPTO>28/02/2024</FEC_EFEC_SPTO><FEC_EMISION>29/02/2024</FEC_EMISION><FEC_EMISION_SPTO>29/02/2024</FEC_EMISION_SPTO><FEC_VALIDEZ>29/02/2024</FEC_VALIDEZ><FEC_VCTO_POLIZA>28/02/2025</FEC_VCTO_POLIZA><FEC_VCTO_SPTO>28/02/2025</FEC_VCTO_SPTO><MCA_DATOS_MINIMOS>N</MCA_DATOS_MINIMOS><MCA_EXCLUSIVO>N</MCA_EXCLUSIVO><MCA_IMPRESION>N</MCA_IMPRESION><MCA_POLIZA_ANULADA>N</MCA_POLIZA_ANULADA><MCA_PRIMA_MANUAL>N</MCA_PRIMA_MANUAL><MCA_PRORRATA>S</MCA_PRORRATA><MCA_PROVISIONAL>N</MCA_PROVISIONAL><MCA_REASEGURO_MANUAL>N</MCA_REASEGURO_MANUAL><MCA_REASEGURO_MARCO>N</MCA_REASEGURO_MARCO><MCA_REGULARIZA>S</MCA_REGULARIZA><MCA_SPTO_ANULADO>N</MCA_SPTO_ANULADO><MCA_SPTO_TMP>N</MCA_SPTO_TMP><MCA_TOMADORES_ALT>N</MCA_TOMADORES_ALT><NUM_APLI>0</NUM_APLI><NUM_CONTRATO></NUM_CONTRATO><NUM_POLIZA></NUM_POLIZA><NUM_POLIZA_GRUPO></NUM_POLIZA_GRUPO><NUM_RENOVACIONES>0</NUM_RENOVACIONES><NUM_RIESGOS>1</NUM_RIESGOS><NUM_SECU_GRUPO></NUM_SECU_GRUPO><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><PCT_AGT>100</PCT_AGT><PCT_AGT2></PCT_AGT2><PCT_AGT3></PCT_AGT3><PCT_AGT4></PCT_AGT4><PCT_REGULARIZA>0</PCT_REGULARIZA><TIP_COASEGURO>0</TIP_COASEGURO><TIP_DOCUM>CNE</TIP_DOCUM><TIP_DURACION>2</TIP_DURACION><TIP_GESTOR>AG</TIP_GESTOR><TIP_POLIZA_TR>F</TIP_POLIZA_TR><TIP_REGULARIZA>0</TIP_REGULARIZA><TIP_SPTO>XX</TIP_SPTO><TXT_MOTIVO_SPTO>C</TXT_MOTIVO_SPTO></ROW></ROWSET></TABLE><TABLE NAME=\"P2000031\"><ROWSET><ROW><COD_CIA>1</COD_CIA><COD_MODALIDAD>11204</COD_MODALIDAD><FEC_EFEC_RIESGO>28/02/2024</FEC_EFEC_RIESGO><FEC_VCTO_RIESGO>28/02/2025</FEC_VCTO_RIESGO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><NOM_RIESGO>HECTOR HERNANDEZ LOPEZ</NOM_RIESGO><NUM_APLI>0</NUM_APLI><NUM_POLIZA></NUM_POLIZA><NUM_RIESGO>1</NUM_RIESGO><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><TIP_SPTO>XX</TIP_SPTO></ROW></ROWSET></TABLE><TABLE NAME=\"P2000020\"><ROWSET><ROW><COD_CAMPO>ID_PROMOTOR</COD_CAMPO><COD_CIA>1</COD_CIA><COD_RAMO>112</COD_RAMO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><NUM_APLI>0</NUM_APLI><NUM_PERIODO>1</NUM_PERIODO><NUM_POLIZA></NUM_POLIZA><NUM_RIESGO>0</NUM_RIESGO><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><TIP_NIVEL>1</TIP_NIVEL><VAL_CAMPO>99998</VAL_CAMPO><VAL_COR_CAMPO>99998</VAL_COR_CAMPO></ROW><ROW num=\"2\"><COD_CAMPO>TIPO_SEGURO</COD_CAMPO><VAL_CAMPO>P</VAL_CAMPO><VAL_COR_CAMPO>P</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"3\"><COD_CAMPO>TIP_COMISION</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"4\"><COD_CAMPO>TIP_IMPRESION</COD_CAMPO><VAL_CAMPO>N</VAL_CAMPO><VAL_COR_CAMPO>N</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"5\"><COD_CAMPO>TIP_DEDUCIBLE</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"6\"><COD_CAMPO>COD_MODALIDAD</COD_CAMPO><VAL_CAMPO>11204</VAL_CAMPO><VAL_COR_CAMPO>11204</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"7\"><COD_CAMPO>VAL_FOLIO_SOLICITUD</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"8\"><COD_CAMPO>FEC_NACIMIENTO</COD_CAMPO><VAL_CAMPO>01011987</VAL_CAMPO><VAL_COR_CAMPO>01011987</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"9\"><COD_CAMPO>MCA_SEXO</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"10\"><COD_CAMPO>DTO_AGENTE_DIR</COD_CAMPO><VAL_CAMPO>99998</VAL_CAMPO><VAL_COR_CAMPO>99998</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>3</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"11\"><COD_CAMPO>ANIOS_DURACION_POLIZA</COD_CAMPO><VAL_CAMPO>2</VAL_CAMPO><VAL_COR_CAMPO>2</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"12\"><COD_CAMPO>TIP_PERFIL_INV</COD_CAMPO><VAL_CAMPO>CON</VAL_CAMPO><VAL_COR_CAMPO>CON</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"13\"><COD_CAMPO>NUM_FUNDOS</COD_CAMPO><VAL_CAMPO>5</VAL_CAMPO><VAL_COR_CAMPO>5</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"14\"><COD_CAMPO>TIP_PRIMAS</COD_CAMPO><VAL_CAMPO>2</VAL_CAMPO><VAL_COR_CAMPO>2</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"15\"><COD_CAMPO>PRIMA_COB_1000</COD_CAMPO><VAL_CAMPO>114.28</VAL_CAMPO><VAL_COR_CAMPO>114.28</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW></ROWSET></TABLE><TABLE NAME=\"P2000025\"><ROWSET><ROW><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><COD_CIA>1</COD_CIA><COD_LISTA>600</COD_LISTA><IMP_OCURRENCIA>0</IMP_OCURRENCIA><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><NUM_APLI>0</NUM_APLI><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_PERIODO>1</NUM_PERIODO><NUM_POLIZA></NUM_POLIZA><NUM_RIESGO>1</NUM_RIESGO><NUM_SECU>1</NUM_SECU><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><TXT_CAMPO></TXT_CAMPO><VAL_CAMPO>0104</VAL_CAMPO></ROW><ROW num=\"2\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>20</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"3\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0111</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"4\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>20</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"5\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0108</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>3</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"6\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>20</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>3</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"7\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0105</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>4</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"8\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>20</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>4</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"9\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0101</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>5</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"10\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>20</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>5</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"11\"><COD_CAMPO>TIP_PRIMA</COD_CAMPO><VAL_CAMPO>UI</VAL_CAMPO><TXT_CAMPO>UNICA INICIAL</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"12\"><COD_CAMPO>FORMA_PAGO</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><TXT_CAMPO>1</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"13\"><COD_CAMPO>IMP_PREMIO_VIDA</COD_CAMPO><VAL_CAMPO>20000</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>4</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"14\"><COD_CAMPO>TIP_PRIMA</COD_CAMPO><VAL_CAMPO>AD</VAL_CAMPO><TXT_CAMPO>ADICIONALES</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"15\"><COD_CAMPO>FORMA_PAGO_AD</COD_CAMPO><VAL_CAMPO>4</VAL_CAMPO><TXT_CAMPO>1</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>3</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"16\"><COD_CAMPO>IMP_PREMIO_VIDA_AD</COD_CAMPO><VAL_CAMPO>20000</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>5</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"17\"><COD_CAMPO>FEC_EFEC_PRIMA_ADI</COD_CAMPO><VAL_CAMPO>29</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>9</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"18\"><COD_CAMPO>FEC_EFEC_PRIMA_AD</COD_CAMPO><VAL_CAMPO>29032024</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>7</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW></ROWSET></TABLE><TABLE NAME=\"P2000060\"><ROWSET><ROW><COD_CIA>1</COD_CIA><COD_DOCUM>00000000000117032189</COD_DOCUM><FEC_NACIMIENTO>01/01/1996</FEC_NACIMIENTO><MCA_BAJA>N</MCA_BAJA><MCA_CALCULO>N</MCA_CALCULO><MCA_PRINCIPAL>N</MCA_PRINCIPAL><MCA_VIGENTE>S</MCA_VIGENTE><NUM_APLI>0</NUM_APLI><NUM_POLIZA></NUM_POLIZA><NUM_RIESGO>1</NUM_RIESGO><NUM_SECU>1</NUM_SECU><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><PCT_PARTICIPACION></PCT_PARTICIPACION><TIP_BENEF>2</TIP_BENEF><TIP_DOCUM>CNE</TIP_DOCUM></ROW></ROWSET></TABLE><TABLE NAME=\"P2000040\"><ROWSET><ROW><COD_CIA>1</COD_CIA><COD_COB>1000</COD_COB><COD_FRANQUICIA></COD_FRANQUICIA><COD_MON_CAPITAL>1</COD_MON_CAPITAL><COD_RAMO>112</COD_RAMO><COD_SECC_REAS>0</COD_SECC_REAS><IMP_AGR_REL_SPTO>0</IMP_AGR_REL_SPTO><IMP_AGR_SPTO>0</IMP_AGR_SPTO><MCA_BAJA_COB>N</MCA_BAJA_COB><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><NUM_APLI>0</NUM_APLI><NUM_PERIODO>1</NUM_PERIODO><NUM_POLIZA></NUM_POLIZA><NUM_RIESGO>1</NUM_RIESGO><NUM_SECU>1</NUM_SECU><NUM_SPTO>0</NUM_SPTO><NUM_SPTO_APLI>0</NUM_SPTO_APLI><SUMA_ASEG>50000</SUMA_ASEG><SUMA_ASEG_SPTO>50000</SUMA_ASEG_SPTO><TASA_COB>0</TASA_COB></ROW><ROW num=\"2\"><COD_COB>1004</COD_COB><SUMA_ASEG>50000</SUMA_ASEG><SUMA_ASEG_SPTO>50000</SUMA_ASEG_SPTO><NUM_SECU>2</NUM_SECU><COD_RAMO>112</COD_RAMO><MCA_BAJA_COB>N</MCA_BAJA_COB><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><COD_FRANQUICIA></COD_FRANQUICIA><COD_MON_CAPITAL>1</COD_MON_CAPITAL><TASA_COB>0</TASA_COB><IMP_AGR_SPTO>0</IMP_AGR_SPTO><IMP_AGR_REL_SPTO>0</IMP_AGR_REL_SPTO><COD_SECC_REAS>0</COD_SECC_REAS><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"3\"><COD_COB>1003</COD_COB><SUMA_ASEG>12500</SUMA_ASEG><SUMA_ASEG_SPTO>12500</SUMA_ASEG_SPTO><NUM_SECU>3</NUM_SECU><COD_RAMO>112</COD_RAMO><MCA_BAJA_COB>N</MCA_BAJA_COB><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><COD_FRANQUICIA></COD_FRANQUICIA><COD_MON_CAPITAL>1</COD_MON_CAPITAL><TASA_COB>0</TASA_COB><IMP_AGR_SPTO>0</IMP_AGR_SPTO><IMP_AGR_REL_SPTO>0</IMP_AGR_REL_SPTO><COD_SECC_REAS>0</COD_SECC_REAS><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW></ROWSET></TABLE></XML>";
            //xml = "<XML ACCION=\"C\" COD_RAMO=\"112\" NUM_POLIZA=\"\"><TABLE NAME=\"P2000030\"><ROWSET><ROW num=\"1\"><ANIOS_MAX_DURACION>2</ANIOS_MAX_DURACION><CANT_RENOVACIONES>1</CANT_RENOVACIONES><COD_AGT>99998</COD_AGT><COD_CUADRO_COM>81</COD_CUADRO_COM><COD_DOCUM>PRUEBA</COD_DOCUM><COD_ENVIO>1</COD_ENVIO><COD_FRACC_PAGO>1</COD_FRACC_PAGO><COD_GESTOR>99998</COD_GESTOR><COD_MON>1</COD_MON><COD_NIVEL1>5</COD_NIVEL1><COD_NIVEL2>18</COD_NIVEL2><COD_NIVEL3>4920</COD_NIVEL3><COD_NIVEL3_CAPTURA>4920</COD_NIVEL3_CAPTURA><COD_RAMO>112</COD_RAMO><COD_USR>APPZALID</COD_USR><DURACION_PAGO_PRIMA>1</DURACION_PAGO_PRIMA><FEC_EFEC_POLIZA>06/02/2024</FEC_EFEC_POLIZA><FEC_EFEC_SPTO>06/02/2024</FEC_EFEC_SPTO><FEC_VCTO_POLIZA>6/2/2026</FEC_VCTO_POLIZA><FEC_VCTO_SPTO>6/2/2026</FEC_VCTO_SPTO><TIP_REGULARIZA>0</TIP_REGULARIZA><PCT_REGULARIZA>0</PCT_REGULARIZA><TIP_DURACION>2</TIP_DURACION><NUM_CONTRATO>11228</NUM_CONTRATO><NUM_POLIZA_GRUPO></NUM_POLIZA_GRUPO><COD_CIA>1</COD_CIA><COD_SECTOR>1</COD_SECTOR><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><COD_COMPENSACION>1</COD_COMPENSACION><NUM_SPTO_APLI>0</NUM_SPTO_APLI><PCT_AGT>100</PCT_AGT><PCT_AGT2>0</PCT_AGT2><PCT_AGT3>0</PCT_AGT3><PCT_AGT4>0</PCT_AGT4><NUM_RIESGOS>1</NUM_RIESGOS><NUM_RENOVACIONES>0</NUM_RENOVACIONES><TIP_COASEGURO>0</TIP_COASEGURO><TIP_SPTO>XX</TIP_SPTO><TXT_MOTIVO_SPTO>C</TXT_MOTIVO_SPTO><MCA_REGULARIZA>S</MCA_REGULARIZA><MCA_TOMADORES_ALT>N</MCA_TOMADORES_ALT><MCA_REASEGURO_MANUAL>N</MCA_REASEGURO_MANUAL><MCA_PRORRATA>S</MCA_PRORRATA><MCA_PRIMA_MANUAL>N</MCA_PRIMA_MANUAL><MCA_PROVISIONAL>N</MCA_PROVISIONAL><MCA_POLIZA_ANULADA>N</MCA_POLIZA_ANULADA><MCA_SPTO_ANULADO>N</MCA_SPTO_ANULADO><MCA_SPTO_TMP>N</MCA_SPTO_TMP><MCA_DATOS_MINIMOS>N</MCA_DATOS_MINIMOS><MCA_IMPRESION>N</MCA_IMPRESION><MCA_EXCLUSIVO>N</MCA_EXCLUSIVO><MCA_REASEGURO_MARCO>N</MCA_REASEGURO_MARCO><TIP_POLIZA_TR>F</TIP_POLIZA_TR><FEC_VALIDEZ>06/02/2024</FEC_VALIDEZ><FEC_EMISION>06/02/2024</FEC_EMISION><FEC_EMISION_SPTO>06/02/2024</FEC_EMISION_SPTO><FEC_ACTU>06/02/2024</FEC_ACTU><TIP_DOCUM>CLM</TIP_DOCUM><TIP_GESTOR>AG</TIP_GESTOR></ROW></ROWSET></TABLE><TABLE NAME=\"P2000031\"><ROWSET><ROW num=\"1\"><FEC_EFEC_RIESGO>06/02/2024</FEC_EFEC_RIESGO><FEC_VCTO_RIESGO>6/2/2026</FEC_VCTO_RIESGO><COD_MODALIDAD>11204</COD_MODALIDAD><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_RIESGO>1</NUM_RIESGO><TIP_SPTO>XX</TIP_SPTO><NOM_RIESGO>Riesgo No. 1 (temporal)</NOM_RIESGO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE></ROW></ROWSET></TABLE><TABLE NAME=\"P2000020\"><ROWSET><ROW num=\"1\"><COD_CAMPO>ID_PROMOTOR</COD_CAMPO><VAL_CAMPO>99998</VAL_CAMPO><VAL_COR_CAMPO>99998</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"2\"><COD_CAMPO>TIPO_SEGURO</COD_CAMPO><VAL_CAMPO>P</VAL_CAMPO><VAL_COR_CAMPO>P</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"3\"><COD_CAMPO>TIP_COMISION</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"4\"><COD_CAMPO>TIP_IMPRESION</COD_CAMPO><VAL_CAMPO>N</VAL_CAMPO><VAL_COR_CAMPO>N</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"5\"><COD_CAMPO>TIP_DEDUCIBLE</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"6\"><COD_CAMPO>COD_MODALIDAD</COD_CAMPO><VAL_CAMPO>11204</VAL_CAMPO><VAL_COR_CAMPO>11204</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"7\"><COD_CAMPO>VAL_FOLIO_SOLICITUD</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>0</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"8\"><COD_CAMPO>FEC_NACIMIENTO</COD_CAMPO><VAL_CAMPO>01011987</VAL_CAMPO><VAL_COR_CAMPO>01011987</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"9\"><COD_CAMPO>MCA_SEXO</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><VAL_COR_CAMPO>1</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"10\"><COD_CAMPO>DTO_AGENTE_DIR</COD_CAMPO><VAL_CAMPO>99998</VAL_CAMPO><VAL_COR_CAMPO>99998</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>3</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"11\"><COD_CAMPO>ANIOS_DURACION_POLIZA</COD_CAMPO><VAL_CAMPO>2</VAL_CAMPO><VAL_COR_CAMPO>2</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>1</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"12\"><COD_CAMPO>TIP_PERFIL_INV</COD_CAMPO><VAL_CAMPO>CON</VAL_CAMPO><VAL_COR_CAMPO>CON</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"13\"><COD_CAMPO>NUM_FUNDOS</COD_CAMPO><VAL_CAMPO>2</VAL_CAMPO><VAL_COR_CAMPO>2</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"14\"><COD_CAMPO>TIP_PRIMAS</COD_CAMPO><VAL_CAMPO>2</VAL_CAMPO><VAL_COR_CAMPO>2</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW><ROW num=\"15\"><COD_CAMPO>PRIMA_COB_1000</COD_CAMPO><VAL_CAMPO>114.28</VAL_CAMPO><VAL_COR_CAMPO>114.28</VAL_COR_CAMPO><COD_RAMO>112</COD_RAMO><NUM_RIESGO>1</NUM_RIESGO><TIP_NIVEL>2</TIP_NIVEL><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_PERIODO>1</NUM_PERIODO><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI></ROW></ROWSET></TABLE><TABLE NAME=\"P2000025\"><ROWSET><ROW num=\"1\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0104</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"2\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>50</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"3\"><COD_CAMPO>CODIGO_FUNDO</COD_CAMPO><VAL_CAMPO>0111</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"4\"><COD_CAMPO>PERCENTAGEM_FUNDO</COD_CAMPO><VAL_CAMPO>50</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>600</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"5\"><COD_CAMPO>TIP_PRIMA</COD_CAMPO><VAL_CAMPO>UI</VAL_CAMPO><TXT_CAMPO>UNICA INICIAL</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"6\"><COD_CAMPO>FORMA_PAGO</COD_CAMPO><VAL_CAMPO>1</VAL_CAMPO><TXT_CAMPO>1</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>2</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"7\"><COD_CAMPO>IMP_PREMIO_VIDA</COD_CAMPO><VAL_CAMPO>3500</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>1</NUM_OCURRENCIA><NUM_SECU>4</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"8\"><COD_CAMPO>TIP_PRIMA</COD_CAMPO><VAL_CAMPO>AD</VAL_CAMPO><TXT_CAMPO>ADICIONALES</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"9\"><COD_CAMPO>FORMA_PAGO_AD</COD_CAMPO><VAL_CAMPO>4</VAL_CAMPO><TXT_CAMPO>1</TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>3</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"10\"><COD_CAMPO>IMP_PREMIO_VIDA_AD</COD_CAMPO><VAL_CAMPO>1500</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>5</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"11\"><COD_CAMPO>FEC_EFEC_PRIMA_ADI</COD_CAMPO><VAL_CAMPO>6</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>9</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW><ROW num=\"12\"><COD_CAMPO>FEC_EFEC_PRIMA_AD</COD_CAMPO><VAL_CAMPO>06032024</VAL_CAMPO><TXT_CAMPO></TXT_CAMPO><COD_LISTA>601</COD_LISTA><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_OCURRENCIA>2</NUM_OCURRENCIA><NUM_SECU>7</NUM_SECU><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_OCURRENCIA>N</MCA_BAJA_OCURRENCIA><IMP_OCURRENCIA>0</IMP_OCURRENCIA></ROW></ROWSET></TABLE><TABLE NAME=\"P2000060\"><ROWSET><ROW num=\"1\"><TIP_BENEF>2</TIP_BENEF><NUM_RIESGO>1</NUM_RIESGO><TIP_DOCUM>CLM</TIP_DOCUM><COD_DOCUM>PRUEBA</COD_DOCUM><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_SECU>1</NUM_SECU><MCA_PRINCIPAL>N</MCA_PRINCIPAL><MCA_CALCULO>N</MCA_CALCULO><MCA_BAJA>N</MCA_BAJA><MCA_VIGENTE>S</MCA_VIGENTE><PCT_PARTICIPACION></PCT_PARTICIPACION><FEC_VCTO_CESION></FEC_VCTO_CESION><IMP_CESION></IMP_CESION></ROW><ROW num=\"2\"><TIP_BENEF>10</TIP_BENEF><NUM_RIESGO>1</NUM_RIESGO><TIP_DOCUM>CLM</TIP_DOCUM><COD_DOCUM>PRUEBA</COD_DOCUM><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_SECU>1</NUM_SECU><MCA_PRINCIPAL>N</MCA_PRINCIPAL><MCA_CALCULO>N</MCA_CALCULO><MCA_BAJA>N</MCA_BAJA><MCA_VIGENTE>S</MCA_VIGENTE><PCT_PARTICIPACION></PCT_PARTICIPACION><FEC_VCTO_CESION></FEC_VCTO_CESION><IMP_CESION></IMP_CESION></ROW></ROWSET></TABLE><TABLE NAME=\"P2000040\"><ROWSET><ROW num=\"1\"><COD_COB>1000</COD_COB><SUMA_ASEG>50000</SUMA_ASEG><SUMA_ASEG_SPTO>50000</SUMA_ASEG_SPTO><COD_FRANQUICIA></COD_FRANQUICIA><COD_RAMO>112</COD_RAMO><COD_CIA>1</COD_CIA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_RIESGO>1</NUM_RIESGO><NUM_PERIODO>1</NUM_PERIODO><NUM_SECU>0</NUM_SECU><COD_MON_CAPITAL>1</COD_MON_CAPITAL><TASA_COB>0</TASA_COB><MCA_BAJA_RIESGO>N</MCA_BAJA_RIESGO><MCA_VIGENTE>S</MCA_VIGENTE><MCA_VIGENTE_APLI>S</MCA_VIGENTE_APLI><MCA_BAJA_COB>N</MCA_BAJA_COB><COD_SECC_REAS>0</COD_SECC_REAS><IMP_AGR_SPTO>0</IMP_AGR_SPTO><IMP_AGR_REL_SPTO>0</IMP_AGR_REL_SPTO></ROW></ROWSET></TABLE><TABLE NAME=\"P2300060_MMX\"><ROWSET><ROW num=\"1\"><FEC_NACIMIENTO>01/01/1987</FEC_NACIMIENTO><MCA_SEXO>1</MCA_SEXO><MCA_FUMA></MCA_FUMA><NUM_POLIZA></NUM_POLIZA><NUM_SPTO>0</NUM_SPTO><NUM_APLI>0</NUM_APLI><NUM_SPTO_APLI>0</NUM_SPTO_APLI><NUM_RIESGO>1</NUM_RIESGO><TIP_BENEF>1</TIP_BENEF><NUM_SECU>1</NUM_SECU><COD_CIA>1</COD_CIA></ROW></ROWSET></TABLE></XML>";
            drResultado = iThirdRepository.setCotizacionEmision(xml, userC );
            logger.info("num_poliza: "+drResultado.get("pnum_poliza")+", error:"+drResultado.get("ptxt_error"));
        }catch(Exception ex){
            ex.printStackTrace();
            logger.info("ERROR Cotizacion.setCotizacionEmision(1) : " + ex.getMessage());
        }
        return drResultado;
    }

    /**
     * Contruye el INICIO de cada nodo en formato XML
     * @param tableName
     * @return XML
     */
    private StringBuffer setInicio(String tableName) {
        StringBuffer objSB = new StringBuffer();
        objSB.append("<TABLE NAME=\"" + tableName + "\"><ROWSET>"); //<ROW num="1">
        return objSB;
    }

    /**
     * Contruye el FIN de cada nodo en formmato XML
     * @return XML
     */
    private StringBuffer setFin() {
        StringBuffer objSB = new StringBuffer();
        objSB.append("</ROWSET></TABLE>");//</ROW>
        return objSB;
    }

    /**
     * Retorna el hostname o address del servidor local
     * @return
     */
    private String getClientHost1() {
        HostUtil hostUtil= new HostUtil();
        return hostUtil.getAddress();
    }
    
    private StringBuffer generaNodoP2000025(StringBuffer cadenaXml, P2000025 objP2000025) {
    	
        cadenaXml.append(setInicio("P2000025"));
        Map<String, String> DATOS_AUX = new Hashtable<>();
        /** Solicitante */
        int rowNum = 1;
        DATOS_AUX.put("COD_CAMPO", "CODIGO_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "0024");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "1");
        DATOS_AUX.put("NUM_SECU", "1");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 2;
        DATOS_AUX.put("COD_CAMPO", "PERCENTAGEM_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "25");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "1");
        DATOS_AUX.put("NUM_SECU", "2");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 3;
        DATOS_AUX.put("COD_CAMPO", "CODIGO_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "0025");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "1");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 4;
        DATOS_AUX.put("COD_CAMPO", "PERCENTAGEM_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "25");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "2");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 5;
        DATOS_AUX.put("COD_CAMPO", "CODIGO_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "0026");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "3");
        DATOS_AUX.put("NUM_SECU", "1");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 6;
        DATOS_AUX.put("COD_CAMPO", "PERCENTAGEM_FUNDO");
        DATOS_AUX.put("VAL_CAMPO", "50");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "600");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "3");
        DATOS_AUX.put("NUM_SECU", "2");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 7;
        DATOS_AUX.put("COD_CAMPO", "TIP_PRIMA");
        DATOS_AUX.put("VAL_CAMPO", "UI");
        DATOS_AUX.put("TXT_CAMPO", "UNICA INICIAL");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "1");
        DATOS_AUX.put("NUM_SECU", "1");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 8;
        DATOS_AUX.put("COD_CAMPO", "FORMA_PAGO");
        DATOS_AUX.put("VAL_CAMPO", "1");
        DATOS_AUX.put("TXT_CAMPO", "1");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "1");
        DATOS_AUX.put("NUM_SECU", "2");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 9;
        DATOS_AUX.put("COD_CAMPO", "IMP_PREMIO_VIDA");
        DATOS_AUX.put("VAL_CAMPO", "100000");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "1");
        DATOS_AUX.put("NUM_SECU", "4");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 10;
        DATOS_AUX.put("COD_CAMPO", "TIP_PRIMA");
        DATOS_AUX.put("VAL_CAMPO", "AD");
        DATOS_AUX.put("TXT_CAMPO", "ADICIONALES");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "1");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 11;
        DATOS_AUX.put("COD_CAMPO", "FORMA_PAGO_AD");
        DATOS_AUX.put("VAL_CAMPO", "4");
        DATOS_AUX.put("TXT_CAMPO", "1");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "3");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 12;
        DATOS_AUX.put("COD_CAMPO", "IMP_PREMIO_VIDA_AD");
        DATOS_AUX.put("VAL_CAMPO", "100000");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "5");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 13;
        DATOS_AUX.put("COD_CAMPO", "FEC_EFEC_PRIMA_ADI");
        DATOS_AUX.put("VAL_CAMPO", "5");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "9");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        rowNum = 14;
        DATOS_AUX.put("COD_CAMPO", "FEC_EFEC_PRIMA_AD");
        DATOS_AUX.put("VAL_CAMPO", "05112023");
        DATOS_AUX.put("TXT_CAMPO", "");
        DATOS_AUX.put("COD_LISTA", "601");
        DATOS_AUX.put("NUM_RIESGO", "1");
        DATOS_AUX.put("NUM_PERIODO", "1");
        DATOS_AUX.put("NUM_OCURRENCIA", "2");
        DATOS_AUX.put("NUM_SECU", "7");
        objP2000025.setDatos(DATOS_AUX);
        cadenaXml.append(objP2000025.getXml(rowNum));
        
        
        cadenaXml.append(setFin());
        logger.info("xml generaNodoP2000025-->"+cadenaXml.toString());
    	return cadenaXml;
    }
}
